# Generated by Django 4.2.9 on 2024-03-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_msg_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='detaail_html',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='msg',
            name='detail',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='worker',
            name='end_work_time',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='helmet_wared',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='start_work_time',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='status',
            field=models.CharField(choices=[('在岗', 'Active'), ('休息', 'Inactive'), ('请假', 'Pending'), ('其他', 'Other')], default='在岗', max_length=100),
        ),
    ]
