# Generated by Django 4.2.9 on 2024-03-25 14:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_msg_detaail_html_msg_detail_worker_end_work_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='address',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='age',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='arrive_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='worker',
            name='department_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='email',
            field=models.EmailField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='emergency_contact',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='gender',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='helmet_wared_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='worker',
            name='phone',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='position_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
